// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.12.4
// source: pkg/proto/net/message.proto

package net

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Specific message types for different content
type BlockMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockData     []byte                 `protobuf:"bytes,1,opt,name=block_data,json=blockData,proto3" json:"block_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockMessage) Reset() {
	*x = BlockMessage{}
	mi := &file_pkg_proto_net_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockMessage) ProtoMessage() {}

func (x *BlockMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_net_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockMessage.ProtoReflect.Descriptor instead.
func (*BlockMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_net_message_proto_rawDescGZIP(), []int{0}
}

func (x *BlockMessage) GetBlockData() []byte {
	if x != nil {
		return x.BlockData
	}
	return nil
}

type TransactionMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionData []byte                 `protobuf:"bytes,1,opt,name=transaction_data,json=transactionData,proto3" json:"transaction_data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransactionMessage) Reset() {
	*x = TransactionMessage{}
	mi := &file_pkg_proto_net_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionMessage) ProtoMessage() {}

func (x *TransactionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_net_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionMessage.ProtoReflect.Descriptor instead.
func (*TransactionMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_net_message_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionMessage) GetTransactionData() []byte {
	if x != nil {
		return x.TransactionData
	}
	return nil
}

// Message represents a generic network message
type Message struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnixNano int64                  `protobuf:"varint,1,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	FromPeerId        []byte                 `protobuf:"bytes,2,opt,name=from_peer_id,json=fromPeerId,proto3" json:"from_peer_id,omitempty"`
	// Use oneof to ensure only one type of content is present
	//
	// Types that are valid to be assigned to Content:
	//
	//	*Message_BlockMessage
	//	*Message_TransactionMessage
	Content       isMessage_Content `protobuf_oneof:"content"`
	Signature     []byte            `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_pkg_proto_net_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_net_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_pkg_proto_net_message_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *Message) GetFromPeerId() []byte {
	if x != nil {
		return x.FromPeerId
	}
	return nil
}

func (x *Message) GetContent() isMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Message) GetBlockMessage() *BlockMessage {
	if x != nil {
		if x, ok := x.Content.(*Message_BlockMessage); ok {
			return x.BlockMessage
		}
	}
	return nil
}

func (x *Message) GetTransactionMessage() *TransactionMessage {
	if x != nil {
		if x, ok := x.Content.(*Message_TransactionMessage); ok {
			return x.TransactionMessage
		}
	}
	return nil
}

func (x *Message) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type isMessage_Content interface {
	isMessage_Content()
}

type Message_BlockMessage struct {
	BlockMessage *BlockMessage `protobuf:"bytes,3,opt,name=block_message,json=blockMessage,proto3,oneof"`
}

type Message_TransactionMessage struct {
	TransactionMessage *TransactionMessage `protobuf:"bytes,4,opt,name=transaction_message,json=transactionMessage,proto3,oneof"`
}

func (*Message_BlockMessage) isMessage_Content() {}

func (*Message_TransactionMessage) isMessage_Content() {}

var File_pkg_proto_net_message_proto protoreflect.FileDescriptor

const file_pkg_proto_net_message_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/proto/net/message.proto\x12\x03net\"-\n" +
	"\fBlockMessage\x12\x1d\n" +
	"\n" +
	"block_data\x18\x01 \x01(\fR\tblockData\"?\n" +
	"\x12TransactionMessage\x12)\n" +
	"\x10transaction_data\x18\x01 \x01(\fR\x0ftransactionData\"\x8a\x02\n" +
	"\aMessage\x12.\n" +
	"\x13timestamp_unix_nano\x18\x01 \x01(\x03R\x11timestampUnixNano\x12 \n" +
	"\ffrom_peer_id\x18\x02 \x01(\fR\n" +
	"fromPeerId\x128\n" +
	"\rblock_message\x18\x03 \x01(\v2\x11.net.BlockMessageH\x00R\fblockMessage\x12J\n" +
	"\x13transaction_message\x18\x04 \x01(\v2\x17.net.TransactionMessageH\x00R\x12transactionMessage\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignatureB\t\n" +
	"\acontentB*Z(github.com/gochain/gochain/pkg/proto/netb\x06proto3"

var (
	file_pkg_proto_net_message_proto_rawDescOnce sync.Once
	file_pkg_proto_net_message_proto_rawDescData []byte
)

func file_pkg_proto_net_message_proto_rawDescGZIP() []byte {
	file_pkg_proto_net_message_proto_rawDescOnce.Do(func() {
		file_pkg_proto_net_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_net_message_proto_rawDesc), len(file_pkg_proto_net_message_proto_rawDesc)))
	})
	return file_pkg_proto_net_message_proto_rawDescData
}

var file_pkg_proto_net_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_net_message_proto_goTypes = []any{
	(*BlockMessage)(nil),       // 0: net.BlockMessage
	(*TransactionMessage)(nil), // 1: net.TransactionMessage
	(*Message)(nil),            // 2: net.Message
}
var file_pkg_proto_net_message_proto_depIdxs = []int32{
	0, // 0: net.Message.block_message:type_name -> net.BlockMessage
	1, // 1: net.Message.transaction_message:type_name -> net.TransactionMessage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_net_message_proto_init() }
func file_pkg_proto_net_message_proto_init() {
	if File_pkg_proto_net_message_proto != nil {
		return
	}
	file_pkg_proto_net_message_proto_msgTypes[2].OneofWrappers = []any{
		(*Message_BlockMessage)(nil),
		(*Message_TransactionMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_net_message_proto_rawDesc), len(file_pkg_proto_net_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_net_message_proto_goTypes,
		DependencyIndexes: file_pkg_proto_net_message_proto_depIdxs,
		MessageInfos:      file_pkg_proto_net_message_proto_msgTypes,
	}.Build()
	File_pkg_proto_net_message_proto = out.File
	file_pkg_proto_net_message_proto_goTypes = nil
	file_pkg_proto_net_message_proto_depIdxs = nil
}
