// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.12.4
// source: pkg/proto/net/message.proto

package net

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Your message definitions below
type Message struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Type              string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload           []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	TimestampUnixNano int64                  `protobuf:"varint,3,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	FromPeerId        []byte                 `protobuf:"bytes,4,opt,name=from_peer_id,json=fromPeerId,proto3" json:"from_peer_id,omitempty"`
	SenderPeerId      []byte                 `protobuf:"bytes,5,opt,name=sender_peer_id,json=senderPeerId,proto3" json:"sender_peer_id,omitempty"`
	Signature         []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_pkg_proto_net_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_net_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_pkg_proto_net_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *Message) GetFromPeerId() []byte {
	if x != nil {
		return x.FromPeerId
	}
	return nil
}

func (x *Message) GetSenderPeerId() []byte {
	if x != nil {
		return x.SenderPeerId
	}
	return nil
}

func (x *Message) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_pkg_proto_net_message_proto protoreflect.FileDescriptor

const file_pkg_proto_net_message_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/proto/net/message.proto\x12\x03net\"\xcd\x01\n" +
	"\aMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12.\n" +
	"\x13timestamp_unix_nano\x18\x03 \x01(\x03R\x11timestampUnixNano\x12 \n" +
	"\ffrom_peer_id\x18\x04 \x01(\fR\n" +
	"fromPeerId\x12$\n" +
	"\x0esender_peer_id\x18\x05 \x01(\fR\fsenderPeerId\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignatureB*Z(github.com/gochain/gochain/pkg/proto/netb\x06proto3"

var (
	file_pkg_proto_net_message_proto_rawDescOnce sync.Once
	file_pkg_proto_net_message_proto_rawDescData []byte
)

func file_pkg_proto_net_message_proto_rawDescGZIP() []byte {
	file_pkg_proto_net_message_proto_rawDescOnce.Do(func() {
		file_pkg_proto_net_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_net_message_proto_rawDesc), len(file_pkg_proto_net_message_proto_rawDesc)))
	})
	return file_pkg_proto_net_message_proto_rawDescData
}

var file_pkg_proto_net_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_proto_net_message_proto_goTypes = []any{
	(*Message)(nil), // 0: net.Message
}
var file_pkg_proto_net_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_net_message_proto_init() }
func file_pkg_proto_net_message_proto_init() {
	if File_pkg_proto_net_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_net_message_proto_rawDesc), len(file_pkg_proto_net_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_net_message_proto_goTypes,
		DependencyIndexes: file_pkg_proto_net_message_proto_depIdxs,
		MessageInfos:      file_pkg_proto_net_message_proto_msgTypes,
	}.Build()
	File_pkg_proto_net_message_proto = out.File
	file_pkg_proto_net_message_proto_goTypes = nil
	file_pkg_proto_net_message_proto_depIdxs = nil
}
