# adrenochain Production Configuration
# This file contains production-ready settings for security and performance

# Security Configuration
security:
  enable_tls: true
  enable_auth: true
  api_key_required: true
  rate_limiting: true
  max_connections: 1000
  
  # Admin whitelist
  admin_whitelist:
    - "0x1234567890123456789012345678901234567890"
    - "0x0987654321098765432109876543210987654321"
  
  # Alert thresholds
  alert_thresholds:
    failed_logins: 5
    suspicious_ips: 10
    api_abuse: 100

# Network Configuration
network:
  listen_port: 8545
  p2p_port: 30303
  max_peers: 100
  enable_mdns: false
  enable_relay: false
  connection_timeout: 30s
  
  # Bootstrap peers
  bootstrap_peers:
    - "/ip4/127.0.0.1/tcp/30303/p2p/12D3KooWProductionNode1"
    - "/ip4/127.0.0.1/tcp/30304/p2p/12D3KooWProductionNode2"

# Blockchain Configuration
blockchain:
  data_dir: "/var/lib/adrenochain/data"
  genesis_block: false
  difficulty: 1000000
  block_time: 15s
  max_block_size: 1048576  # 1MB

# Mining Configuration
mining:
  enabled: true
  threads: 8
  reward_address: "0x1234567890123456789012345678901234567890"
  gas_limit: 8000000
  gas_price: 20000000000  # 20 Gwei

# Storage Configuration
storage:
  engine: "leveldb"
  cache_size: "2GB"
  write_buffer_size: "128MB"
  max_open_files: 1000
  compression: true

# Wallet Configuration
wallet:
  encryption_enabled: true
  key_derivation_iterations: 100000
  backup_enabled: true
  backup_interval: "24h"
  backup_retention: 30

# Logging Configuration
logging:
  level: "info"
  format: "json"
  output: "file"
  file_path: "/var/log/adrenochain/app.log"
  max_size: "100MB"
  max_age: 30
  max_backups: 10
  
  # Structured logging
  enable_structured_logging: true
  include_timestamp: true
  include_level: true
  include_caller: true

# Monitoring Configuration
monitoring:
  enable_metrics: true
  metrics_port: 9090
  enable_prometheus: true
  enable_grafana: true
  
  # Health checks
  health_check_interval: 30s
  health_check_timeout: 10s
  
  # Performance metrics
  collect_performance_metrics: true
  collect_network_metrics: true
  collect_storage_metrics: true

# Performance Configuration
performance:
  max_goroutines: 10000
  gc_percent: 100
  memory_limit: "8GB"
  cpu_profiling: false
  memory_profiling: false

# DeFi Configuration
defi:
  enable_amm: true
  enable_lending: true
  enable_governance: true
  enable_oracle: true
  
  # Gas optimization
  gas_optimization: true
  batch_processing: true
  
  # Security
  max_slippage: 500  # 5%
  liquidation_threshold: 8000  # 80%
  liquidation_bonus: 500  # 5%
